Enable arithmetic_paramse for goldilocks64
NilFoundation/crypto3-algebra pull request #137
Opened 2024-02-26 07:25 UTC by akokoshn

2024-02-26 10:21 UTC, martun approved these changes

2024-02-28 07:59 UTC, ETatuzova requested changes

2024-02-28 07:59 UTC, ETatuzova commented on include/nil/crypto3/algebra/fields/arithmetic_params/goldilocks64.hpp
> +                    constexpr static const integral_type geometric_generator = 0x02;
Ok. Not used in placeholder but can be used for geometric_domain. Tests passed successfully

2024-02-28 07:59 UTC, ETatuzova commented on include/nil/crypto3/algebra/fields/arithmetic_params/goldilocks64.hpp
> +                    constexpr static const integral_type nqr = 0x05;
Not used, let's remove

2024-02-28 07:59 UTC, ETatuzova commented on include/nil/crypto3/algebra/fields/arithmetic_params/goldilocks64.hpp
> +                constexpr typename arithmetic_params<goldilocks64_base_field>::integral_type const
Not used. Let's remove

2024-02-28 09:27 UTC, akokoshn commented on include/nil/crypto3/algebra/fields/arithmetic_params/goldilocks64.hpp
> +                    constexpr static const integral_type multiplicative_generator = 0x05;
done

2024-02-29 06:42 UTC, ETatuzova approved these changes

2024-02-29 07:15 UTC, merged